mc_gross=0.01
protection_eligibility=Eligible
address_status=confirmed
payer_id=U7383M9YJMEJU
tax=0.00
address_street=1810 Pineview Circle
payment_date=20:32:26 Sep 20, 2010 PDT
payment_status=Completed
charset=windows-1252
address_zip=32792
first_name=eric
mc_fee=0.01
address_country_code=US
address_name=Erockgamer
notify_version=3.0
custom='1'
payer_status=verified
business=info@preownedgowns.com
address_country=United States
address_city=Winter Park
quantity=1
verify_sign=AGs52InFHk3cJ5j80u2Udq.A26J4AB7BbyqUIgJlbQ3jXePgM3IJabTS
payer_email=erockgamer@yahoo.com
txn_id=1AA71082R3575514U
payment_type=instant
payer_business_name=Erockgamer
btn_id=20222574
last_name=silvay
address_state=FL
receiver_email=info@preownedgowns.com
payment_fee=0.01
shipping_discount=0.00
insurance_amount=0.00
receiver_id=9TVJESTAGXW4W
txn_type=web_accept
item_name=PreOwnedGowns.com Gown Listing
discount=0.00
mc_currency=USD
item_number=
residence_country=US
shipping_method=Default
handling_amount=0.00
transaction_subject='1'
payment_gross=0.01
shipping=0.00